[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nazm"
version = "0.1.0"
description = "Vision system for UI automation"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "opencv-python",
    "numpy",
    "mss",
    "pyautogui",
]

[tool.setuptools.packages.find]
where = ["src"]