name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Roda quando você subir uma tag como v0.1.0

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Esta permissão é essencial para autenticação sem senha (OIDC)
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: python -m pip install build

      - name: Build binary wheel and source tarball
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
